datos_entrenamiento = [

    ["hola", "saludo"],
    ["hola buenos dias", "saludo"],
    ["buenas tardes", "saludo"],
    ["buenas noches", "saludo"],
    ["hola que tal", "saludo"],
    ["buenas noches estimad@s", "saludo"],
    ["hey hola", "saludo"],
    ["buen día", "saludo"],
    ["saludos", "saludo"],
    ["hola como estas", "saludo"],
    ["que tal", "saludo"],
    ["buenas", "saludo"],
    ["hello", "saludo"],
    ["hi", "saludo"],
    ["buenos dias", "saludo"],
    ["como estan", "saludo"],
    ["hola bot", "saludo"],
    ["iniciar", "saludo"],
    ["empezar", "saludo"],
    ["hay alguien ahi", "saludo"],
    ["holi", "saludo"],
    ["alo", "saludo"],
    ["buen dia", "saludo"],


    ["el precio es muy alto", "queja"],
    ["muy caro el producto", "queja"],
    ["es una estafa", "queja"],
    ["subieron el precio", "queja"],
    ["el pedido nunca llegó", "queja"],
    ["la caja vino golpeada", "queja"],
    ["producto roto", "queja"],
    ["pésimo servicio", "queja"],
    ["no me dura la batería", "queja"],
    ["quiero devolverlo", "queja"],
    ["estoy molesto", "queja"],
    ["demora mucho", "queja"],
    ["no sirve", "queja"],
    ["se calienta mucho", "queja"],
    ["exijo devolución", "queja"],
    ["quiero mi dinero", "queja"],
    ["son unos ladrones", "queja"],
    ["mala atencion", "queja"],
    ["no me gusto", "queja"],
    ["horrible experiencia", "queja"],
    ["no lo recomiendo", "queja"],
    ["llego tarde", "queja"],
    ["no funciona bien", "queja"],
    ["es un robo", "queja"],
    ["muy costoso", "queja"],
    ["mala calidad", "queja"],
    ["estoy decepcionado", "queja"],
    ["fraude", "queja"],
    ["basura de producto", "queja"],


    ["ubicacion", "ubicacion"],
    ["donde estan ubicados", "ubicacion"],
    ["donde queda la tienda", "ubicacion"],
    ["me pasas la ubicacion", "ubicacion"],
    ["direccion por favor", "ubicacion"],
    ["tienen tienda fisica", "ubicacion"],
    ["donde los encuentro", "ubicacion"],
    ["en que calle estan", "ubicacion"],
    ["mandame el mapa", "ubicacion"],
    ["quiero ir a la tienda", "ubicacion"],
    ["donde es el local", "ubicacion"],
    ["ubicacion gps", "ubicacion"],
    ["donde recojo", "ubicacion"],
    ["lugar de entrega", "ubicacion"],
    ["ciudad y direccion", "ubicacion"],
    ["donde se encuentran", "ubicacion"],
    ["pasame la dire", "ubicacion"],
    ["donde queda", "ubicacion"],
    ["ubicacion exacta", "ubicacion"],
    ["croquis", "ubicacion"],
    ["mapa", "ubicacion"],
    ["direccion", "ubicacion"],


    ["necesito ayuda", "soporte"],
    ["ayuda por favor", "soporte"],
    ["no puedo conectar el bluetooth", "soporte"],
    ["mi pantalla se puso negra", "soporte"],
    ["como configuro el wifi", "soporte"],
    ["error al instalar", "soporte"],
    ["el equipo no enciende", "soporte"],
    ["necesito un técnico", "soporte"],
    ["revisar mi compu", "soporte"],
    ["reseteo de fábrica", "soporte"],
    ["no reconoce la sim", "soporte"],
    ["audio entrecortado", "soporte"],
    ["tengo un problema tecnico", "soporte"],
    ["no carga", "soporte"],
    ["se apaga solo", "soporte"],
    ["pantalla rota", "soporte"],
    ["bateria hinchada", "soporte"],
    ["no funciona la camara", "soporte"],
    ["ayuda tecnica", "soporte"],
    ["soporte tecnico", "soporte"],
    ["fallo de sistema", "soporte"],
    ["mi celular murio", "soporte"],
    ["no prende", "soporte"],
    ["se traba mucho", "soporte"],
    ["lento", "soporte"],
    ["virus", "soporte"],
    ["reparacion", "soporte"],


    ["catalogo", "catalogo"],
    ["quiero ver el catalogo", "catalogo"],
    ["que productos venden", "catalogo"],
    ["productos disponibles", "catalogo"],
    ["enviame el catalogo", "catalogo"],
    ["lista de precios", "catalogo"],
    ["tienes pdf de productos", "catalogo"],
    ["muestrame que tienes", "catalogo"],
    ["precio de todo", "catalogo"],
    ["ver productos", "catalogo"],
    ["menu de productos", "catalogo"],
    ["catalgo", "catalogo"], 
    ["catologo", "catalogo"], 
    ["info de precios", "catalogo"],
    ["que vendes", "catalogo"],
    ["disponible", "catalogo"],
    ["stock", "catalogo"],
    ["lista", "catalogo"],
    ["folleto", "catalogo"],
    ["inventario", "catalogo"],
    ["disponible","catalogo"],


    ["quiero comprar un celular", "iphone"],
    ["celular", "iphone"],
    ["que celulares tiene", "iphone"],
    ["que iphones tiene", "iphone"],
    ["iphone", "iphone"],
    ["precio del iphone", "iphone"],
    ["iphone 15", "iphone"],
    ["iphone 14 pro", "iphone"],
    ["iphone 13", "iphone"],
    ["iphone 12", "iphone"],
    ["iphone 16", "iphone"],
    ["venden celulares", "iphone"],
    ["moviles apple", "iphone"],
    ["cuanto cuesta el iphone", "iphone"],
    ["modelos de iphone", "iphone"],
    ["quiero un telefono", "iphone"],
    ["smartphone", "iphone"],
    ["dispositivos apple", "iphone"],
    ["comprar iphone", "iphone"],
    ["me interesa un iphone", "iphone"],
    ["busco celular", "iphone"],
    ["tienes el ultimo iphone", "iphone"],
    ["iphone pro max", "iphone"],
 


    ["que audifonos tienen", "accesorios"],
    ["accesorios", "accesorios"],
    ["cargador", "accesorios"],
    ["audifonos", "accesorios"],
    ["airpods", "accesorios"],
    ["cable usb", "accesorios"],
    ["auriculares", "accesorios"],
    ["tienes cargadores", "accesorios"],
    ["magsafe", "accesorios"],
    ["accesorios para celular", "accesorios"],
    ["quiero unos audifonos", "accesorios"],
    ["cables", "accesorios"],
    
    


    ["macanas", "macanas"],
    ["asdfkajdlfa", "macanas"],
    ["no entiendo nada", "macanas"],
    ["blablabla", "macanas"],
    ["jajaja", "macanas"],
    ["cualquier cosa", "macanas"],
    ["xyz", "macanas"],
    ["12345", "macanas"],
    ["fsdfsd", "macanas"],
    ["...", "macanas"],
    ["kljsdfg", "macanas"],
    ["ñlkjh", "macanas"],
    ["futbol", "macanas"],
    ["politica", "macanas"],
    ["clima", "macanas"],
    ["receta de cocina", "macanas"],
    ["chiste", "macanas"],
    ["cuentame algo", "macanas"],
    ["aburrido", "macanas"],
    ["tonto", "macanas"],
    ["feo", "macanas"],
    ["nada", "macanas"]
]
